person:
  first-name: 田
  name: 杰熠
  age: 28
  birth: 1991/10/17
  boss: true
  maps: {one: 张三, two: 李四}
  list: [王五,孙六]
  car:
    name: ${person.name}_凯迪拉克
    price: ${random.long(500000)}


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.1.205:3306/class_brand?characterEncoding\=UTF-8&useUnicode\=true&allowMultiQueries\=true
    username: root
    password: 123456