spring:
  profiles:
    active: dev
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 30
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
mybatis:
  mapper-locations: classpath:sql/*.xml
person:
  first-name: 田
  name: 杰熠
  age: 28
  birth: 1991/10/17
  boss: true
  maps: {one: 张三, two: 李四}
  list: [王五,孙六]
  car:
    name: ${person.name}_凯迪拉克
    price: ${random.long(500000)}
---
spring:
  profiles: pro
  datasource:
    url:  jdbc:mysql://192.168.0.110:3306/testdata?characterEncoding\=UTF-8&useUnicode\=true&allowMultiQueries\=true
    username: root
    password: root
server:
  port: 8000
---
spring:
  profiles: dev
  datasource:
    url:  jdbc:mysql://192.168.0.110:3306/testdata?characterEncoding\=UTF-8&useUnicode\=true&allowMultiQueries\=true
    username: root
    password: root
    filters: stat,wall,log4j
    use-global-data-source-stat: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  output:
    ansi:
      enabled: always
server:
  port: 80
logging:
  level:
    pers:
      jaye:
        springbootdemo:
          mapper: debug